# -*- coding: utf-8-unix -*-
#+TITLE:     On Emacs
#+AUTHOR:    Hideki Saito
#+EMAIL:     hidekis@gmail.com
#+DESCRIPTION: Some history with and thought about Emacs by Hideki Saito
#+KEYWORDS: Emacs, history, opinion, essay, software 
#+STYLE: <link rel="stylesheet" type="text/css" href="style.css" />
#+STYLE: <script type="text/javascript">
#+STYLE:   (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
#+STYLE:   (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
#+STYLE:   m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
#+STYLE:   })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
#+STYLE: 
#+STYLE:   ga('create', 'UA-114515-36', 'hclippr.org');
#+STYLE:   ga('send', 'pageview');
#+STYLE: 
#+STYLE: </script>
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP: index.html
#+LINK_HOME: index.html
#+XSLT:

* How did I get to know Emacs?
I have been using Emacs for about 10 years now. Before Emacs, I have used many different text editors. I've used [[http://hide.maruo.co.jp/software/hidemaru.html][Hidemaru editor]][fn::Also known as /Maruo Editor/], [[http://sakura-editor.sourceforge.net/][Sakura Editor]] and others. 

One day I have encountered [[http://www.jsdlab.co.jp/~kamei/][xyzzy]]. /Xyzzy/ is an editor similar to Emacs, but uses [[http://en.wikipedia.org/wiki/Common_Lisp][Common Lisp]]. It is an excellent editor with good integration to [[http://windows.microsoft.com/][Windows]] ecosystem[fn::For instance, it could call function of Windows DLL]. Problem of /xyzzy/ is that it is Windows only. Around 2004, I have been started using a [[http://www.apple.com/][Mac]], and I needed something that works across the platform. Therefore, I decided port my environment for Emacs. Actually, on Windows (at work, and home) I used Emacs variant called [[http://www.meadowy.org/meadow/][Meadow]] as it supported Japanese language better. I've used Emacs (for portable) on a Mac.

That was when I was working at [[http://en.wikipedia.org/wiki/Amaze_Entertainment][Amaze Entertainment]] and I have been using Meadow/Emacs for most of coding in [[http://en.wikipedia.org/wiki/Lua_(programming_language)][Lua]] and [[http://en.wikipedia.org/wiki/C%2B%2B][C++]]. It was so powerful, and was highly portable.[fn::If you are using Emacs and happened to be in the video game industry, please join [[https://plus.google.com/communities/110828308901706714382][Emacs Users in the Video Game Industry]]!] There was one day my PC has crashed, and while IT was busy fixing my machine, I could sit at the workstation used by someone who was away on his vacation, and continue working with the environment I'm used to.

After I left Amaze for another company, because I was doing a more producer type of work, I haven't been using Emacs for a while. However, the recent discovery of [[http://orgmode.org/][Org-mode]] and increased needs for web development is making me come back to Emacs for many of my daily tasks.

Today, I use Emacs on [[http://www.linux.org][Linux]], Mac, and Windows. My sub-department at [[http://www.sakuracon.org/][Sakura-Con]] also used Emacs and Org-mode extensively for planning, and publishing.

* What's my favorite feature on Emacs?
- [[http://orgmode.org/][Org-mode]]


* About Hideki Saito
Hideki Saito is a producer with many years of experience in technology field, mainly in the video game industry. Past experiences including Lua coding for video game event scripting as well as UI composition. Hideki also manages Japanese Guest Relations team at Asia Northwest Cultural Education Association/Sakura-Con as a Japanese Guest Manager since 2003. (Initially started as Japanese Guest Liaison in 2002.)
- For personal inquiries: [[https://plus.google.com/+HidekiSaito?rel=author][Hideki Saito at Google+]]
- For professional inquiries: [[http://www.linkedin.com/in/hideki/][Hideki Saito at LinkedIn]]
